### ISSUE TITLE
Latest Update doing update error.

### ISSUE THREAD

**Issue by miri4ever** [Sajaki/PBWoW3ext#15]
Wanted to update from 3.2 to 3,2.1 Version with latest Github Version but getting this kind of error if I try to enable extension:

Allgemeiner Fehler
SQL ERROR [ mysqli ]

Table 'xxxx.PHP3_pbwowext_config' doesn't exist [1146]

SQL

DELETE FROM PHP3_pbwowext_config WHERE config_name = 'topbar_code'

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/phpbb/db/driver/driver.php
LINE: 999
CALL: trigger_error()

FILE: [ROOT]/phpbb/db/driver/mysqli.php
LINE: 193
CALL: phpbb\db\driver\driver->sql_error()

FILE: [ROOT]/phpbb/db/driver/factory.php
LINE: 329
CALL: phpbb\db\driver\mysqli->sql_query()

FILE: [ROOT]/ext/paybas/pbwowext/migrations/release_3_2_1_data.php
LINE: 48
CALL: phpbb\db\driver\factory->sql_query()

FILE: (not given by php)
LINE: (not given by php)
CALL: paybas\pbwowext\migrations\release_3_2_1_data->pbwow_update_data()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 711
CALL: call_user_func_array()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 658
CALL: phpbb\db\migrator->run_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 436
CALL: phpbb\db\migrator->process_data_step()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 288
CALL: phpbb\db\migrator->try_apply()

FILE: [ROOT]/phpbb/db/migrator.php
LINE: 241
CALL: phpbb\db\migrator->update_do()

FILE: [ROOT]/phpbb/extension/base.php
LINE: 78
CALL: phpbb\db\migrator->update()

FILE: [ROOT]/ext/javiexin/extension/extension/manager.php
LINE: 196
CALL: phpbb\extension\base->enable_step()

FILE: [ROOT]/ext/boardtools/upload/includes/functions/extensions.php
LINE: 333
CALL: javiexin\extension\extension\manager->enable_step()

FILE: [ROOT]/ext/boardtools/upload/acp/upload_module.php
LINE: 173
CALL: boardtools\upload\includes\functions\extensions::enable()

FILE: [ROOT]/includes/functions_module.php
LINE: 676
CALL: boardtools\upload\acp\upload_module->main()

FILE: [ROOT]/adm/index.php
LINE: 82
CALL: p_master->load_active()

**Comment by avandenberghe** [comment]
Please disable your installed pbwowext extension and then click "delete data". 

and then install again from http://www.avathar.be/bbdkp/app.php/dl_ext/?view=detail&df_id=37

you should then see this table 
```
CREATE TABLE `PHP3_pbwowext_config` (
  `config_name` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `config_value` mediumtext COLLATE utf8_bin NOT NULL,
  `config_default` mediumtext COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`config_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
